#https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/

apiVersion: 1
groups:
    - orgId: 1
      name: critical-alerts
      folder: TestFolder
      interval: 1m
      rules:
        - uid: cefesuansabcwa
          title: alertmanager-down
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: DS_PROMETHEUS_UID
              model:
                editorMode: code
                expr: count(alertmanager_cluster_members)
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 2
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            env: pro
            owner: sre
            projectKey: ALERTING
            severity: critical
          isPaused: false
          notification_settings:
            receiver: test-webhook
