global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3100' ]
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    # only grab metrics with 'otelchi'
    #metric_relabel_configs:
    #  - source_labels: [__name__]
    #    regex: '.*otelchi.*'
    #    action: keep

  - job_name: grafana1
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - grafana-node-1:3000

  - job_name: grafana2
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - grafana-node-2:3000

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - 'rules/1.basic.yml'
  #- 'rules/2.absent.yml'
  #- 'rules/3.group.yml'
  #- 'rules/4.templating.yml'
  # restart prometheus          