receivers:
  # setting up how we receive data from our services
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # bundle up the data before sending it out
  batch:

exporters:
  # send metrics to otlp
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "otelchi"
    const_labels:
      env: development
      app: example
      source: otel
  # send traces to OTLP
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  # keep some logs around for when we need to debug stuff
  debug:
    verbosity: normal #detailed or basic

service:
  # here is where everything sets
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
