groups:
  - name: templating
    rules:
      - alert: HighCPU
        expr: avg_over_time(cpu_usage[5m])>80
        for: 0s  # pending period
        labels:
          severity: critical
        annotations:
          summary: "CPU usage for instance {{ $labels.instance }} excedded 80%"
