#https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/

apiVersion: 1
groups:
    - orgId: 1
      name: critical-alerts
      folder: Critical Alerts
      interval: 10s
      rules:
        - uid: cefesuansabcwa
          title: alertmanager-down
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: prometheus
              model:
                editorMode: code
                expr: count(alertmanager_cluster_members)
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 2
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 5s
          annotations:
            summary: "Grafana alerting node down"
          isPaused: false            
          labels:
            env: pro
            owner: sre
            project_key: ALERTING
            severity: critical
            alertname: alertmanager-down
          notification_settings:
            receiver: test-webhook
            group_by: ['project_key', 'alertname']
